In [ ]:
import numpy as np

In [ ]:
# Задание 1
a = np.array([[1, 2, 1], [-2, 1, 1]])
b = np.array([[3, 1], [-1, 0], [2, 4]])
c = np.array([[-2, 2], [1, -1], [1, 2]])

# 1) a + 2 * b
b_transposed = np.transpose(b)
result1 = a + 2 * b_transposed

# 2) b + 2 * c
result2 = b + 2 * c

print("Результат выражения a + 2 * b:")
print(result1)

print("Результат выражения b + 2 * c:")
print(result2)

Результат выражения a + 2 * b:
[[7 0 5]
 [0 1 9]]
Результат выражения b + 2 * c:
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [ ]:
# Задание 2
# Создание матрицы 8x8 из нулей
matrix = np.zeros((8, 8), dtype=int)

# Заполнение матрицы значениями в шахматном порядке
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Задание 3
# 1)
first_vector = np.arange(0, 1.5, 0.1)
second_vector = np.arange(1, 7)

print("Первый вектор: ", first_vector)
print("Второй вектор: ", second_vector)

# 2)
first_matrix = first_vector.reshape(5, 3)
second_matrix = second_vector.reshape(3, 2)
result_matrix = np.dot(first_matrix, second_matrix)

print("Первая матрица: ",first_matrix)
print("Вторая матрица: ",second_matrix)
print("Результат перемножения матриц: ",result_matrix)

Первый вектор:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
Второй вектор:  [1 2 3 4 5 6]
Первая матрица:  [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
Вторая матрица:  [[1 2]
 [3 4]
 [5 6]]
Результат перемножения матриц:  [[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]
